import Banner from '../components/banner/banner';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home = () => {
	const handleOnBannerBtnClick = () => {
		console.log('Clicked');
	};

	return (
		<>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Banner
					buttonText='View stores nearby'
					onClick={handleOnBannerBtnClick}
				/>
				<div className={styles.heroImage}>
					<Image
						src='/static/hero-image.png'
						width={700}
						height={400}
						alt='hero image'
					/>
				</div>
			</main>
		</>
	);
};

export default Home;
