import Banner from '../components/banner/banner';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home = () => {
	const handleOnBannerBtnClick = () => {
		console.log('Clicked');
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>Coffee Connoisseur</h1>
				<Banner
					buttonText='View stores nearby'
					onClick={handleOnBannerBtnClick}
				/>
			</main>
		</>
	);
};

export default Home;
